"""CI status monitoring for agent-created pull requests.

After the Implementation Agent opens a PR, the CI monitor polls the PR's
check runs.  If any check fails, the monitor diagnoses the failure using
the LLM and pushes a fix to the same branch — fully automated CI repair.

Designed to be invoked as a scheduled workflow step or triggered by
``check_run.completed`` events.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from repokeeper.git_ops import git
from repokeeper.llm_client import LLMClient, parse_llm_json
from repokeeper.logs import get_logger
from repokeeper.patrol import (
    _fetch_ci_log_snippet,
    _get_gh_token_from_client,
)
from repokeeper.profile import load_profile

logger = get_logger("ci-monitor")


@dataclass
class CheckResult:
    """A single check run on a PR."""

    name: str
    status: str           # "queued" | "in_progress" | "completed"
    conclusion: str       # "success" | "failure" | "neutral" | "cancelled" | "timed_out" | "action_required"
    url: str
    run_id: int = 0
    completed_at: datetime | None = None


@dataclass
class PRCheckStatus:
    """Aggregate check status for a pull request."""

    pr_number: int
    total_checks: int = 0
    completed: int = 0
    passed: int = 0
    failed: list[CheckResult] = field(default_factory=list)
    in_progress: list[CheckResult] = field(default_factory=list)
    overall: str = "pending"  # "pending" | "success" | "failure"


def get_pr_check_status(
    gh_client: Any,
    repo: str,
    pr_number: int,
) -> PRCheckStatus:
    """Query the GitHub Checks API for the latest status of a PR.

    Args:
        gh_client: PyGithub Github instance.
        repo: Repository slug (owner/repo).
        pr_number: Pull request number.

    Returns:
        PRCheckStatus with all checks aggregated.
    """
    status = PRCheckStatus(pr_number=pr_number)

    try:
        gh_repo = gh_client.get_repo(repo)
        pr = gh_repo.get_pull(pr_number)
        head_sha = pr.head.sha

        # Get check runs for the head commit
        check_runs = gh_repo.get_commit(head_sha).get_check_runs()

        for run in check_runs:
            check = CheckResult(
                name=run.name,
                status=str(run.status or ""),
                conclusion=str(run.conclusion or ""),
                url=str(run.html_url or ""),
                run_id=int(getattr(run, "id", 0) or 0),
                completed_at=(
                    run.completed_at.replace(tzinfo=timezone.utc)
                    if getattr(run, "completed_at", None) else None
                ),
            )

            status.total_checks += 1

            if check.status == "completed":
                status.completed += 1
                if check.conclusion == "success":
                    status.passed += 1
                elif check.conclusion in ("failure", "cancelled", "timed_out", "action_required"):
                    status.failed.append(check)
            else:
                status.in_progress.append(check)

        # Determine overall status
        if status.total_checks == 0:
            status.overall = "pending"
        elif status.in_progress:
            status.overall = "pending"
        elif status.failed:
            status.overall = "failure"
        elif status.completed == status.passed:
            status.overall = "success"
        else:
            status.overall = "pending"

    except Exception as exc:
        logger.warning("Failed to get check status for PR #%d: %s", pr_number, exc)

    return status


def find_agent_prs(
    gh_client: Any,
    repo: str,
    max_prs: int = 10,
) -> list[int]:
    """Find open PRs created by the RepoKeeper agent (by branch name or body).

    Searches for PRs with branches starting with ``repokeeper/`` or whose
    body contains the RepoKeeper marker.

    Args:
        gh_client: PyGithub Github instance.
        repo: Repository slug (owner/repo).
        max_prs: Maximum number of PRs to return.

    Returns:
        List of PR numbers.
    """
    agent_prs: list[int] = []

    try:
        gh_repo = gh_client.get_repo(repo)
        pulls = gh_repo.get_pulls(state="open", sort="updated", direction="desc")

        for pr in pulls:
            if len(agent_prs) >= max_prs:
                break

            # Check branch name
            if pr.head.ref.startswith("repokeeper/"):
                agent_prs.append(pr.number)
                continue

            # Check body for RepoKeeper marker
            body = pr.body or ""
            if "Generated by RepoKeeper" in body or "🤖 RepoKeeper" in body:
                agent_prs.append(pr.number)
                continue

    except Exception as exc:
        logger.warning("Failed to find agent PRs: %s", exc)

    return agent_prs


CI_FIX_AGENT_PROMPT = """\
You are a DevOps engineer. A RepoKeeper agent PR has failing CI checks.
Your job is to diagnose the failure from the CI logs and produce a minimal
fix that makes the checks pass.

Rules:
- Only fix the actual CI failures. Do not refactor or add features.
- The PR already has code changes on it — you may adjust those changes
  or touch new files if needed.
- Never modify .github/workflows/ (blocked).
- Provide a concrete, targeted fix.

Respond with a single valid JSON object:

{
  "skip": false,
  "reason": "",
  "summary": "One sentence describing the fix.",
  "commit_message": "fix: short imperative message",
  "edits": [
    {
      "path": "path/to/file.py",
      "find": "exact text to replace",
      "replace": "replacement text",
      "replace_all": false
    }
  ],
  "patch": "optional unified diff",
  "changes": {},
  "new_files": {}
}

Set skip=true only if the CI failure cannot be fixed through code changes.
"""


def diagnose_and_fix_ci(
    gh_client: Any,
    llm: LLMClient,
    repo: str,
    pr_number: int,
    profile: dict,
    repo_path: Path = Path("."),
) -> dict[str, Any]:
    """Diagnose a CI failure on an agent PR and push a fix.

    Args:
        gh_client: PyGithub Github instance.
        llm: LLM client.
        repo: Repository slug.
        pr_number: PR number with failing CI.
        profile: Maintainer profile.
        repo_path: Local repository path.

    Returns:
        Dict with ``fixed`` (bool), ``summary``, ``fixes_applied`` (list).
    """
    status = get_pr_check_status(gh_client, repo, pr_number)

    if status.overall != "failure":
        return {
            "fixed": False,
            "summary": f"PR #{pr_number} CI is not failing (status: {status.overall})",
            "fixes_applied": [],
        }

    logger.info(
        "PR #%d has %d failing check(s): %s",
        pr_number,
        len(status.failed),
        ", ".join(ch.name for ch in status.failed),
    )

    # Focus on the first failing check
    check = status.failed[0]
    model = profile.get("agent", {}).get("model", "deepseek-chat")

    try:
        # Fetch CI log data
        log_snippet = _fetch_ci_log_snippet(
            gh_client,
            repo,
            run_id=check.run_id,
            workflow_name=check.name,
            conclusion=check.conclusion,
            run_url=check.url,
        )

        gh_repo = gh_client.get_repo(repo)
        pr = gh_repo.get_pull(pr_number)

        # Checkout the PR branch
        gh_token = _get_gh_token_from_client(gh_client)
        local_branch = f"repokeeper-ci-fix-{pr_number}"

        git("config", "user.email", "repokeeper[bot]@users.noreply.github.com",
            check=False, capture=True, cwd=repo_path)
        git("config", "user.name", "repokeeper[bot]",
            check=False, capture=True, cwd=repo_path)
        git("fetch", "origin", f"pull/{pr_number}/head:refs/remotes/origin/pr/{pr_number}",
            check=False, capture=True, cwd=repo_path)
        git("checkout", "-b", local_branch, f"origin/pr/{pr_number}",
            check=False, capture=True, cwd=repo_path)

        # Get the diff to understand what the agent changed
        diff = git("diff", f"origin/{gh_repo.default_branch}...HEAD",
                    capture=True, check=False, cwd=repo_path).stdout

        user_prompt = f"""\
## CI Failure on PR #{pr_number}

**Check:** {check.name}
**Conclusion:** {check.conclusion}
**URL:** {check.url}

### CI Log
{log_snippet[:3000]}

### PR Diff (what changed)
```diff
{diff[:4000]}
```

Diagnose the CI failure and produce a fix.
"""

        response = llm.chat(
            system=CI_FIX_AGENT_PROMPT,
            messages=[{"role": "user", "content": user_prompt}],
            model=model,
            temperature=0.1,
            max_tokens=4000,
            stream=False,
        )

        fix_result = parse_llm_json(response.content.strip())

        if fix_result.get("skip"):
            reason = fix_result.get("reason", "Could not fix automatically.")
            logger.info("CI fix skipped: %s", reason)
            git("checkout", gh_repo.default_branch, check=False, capture=True, cwd=repo_path)
            return {
                "fixed": False,
                "summary": f"CI fix on PR #{pr_number} skipped: {reason}",
                "fixes_applied": [],
            }

        # Apply the fix
        from repokeeper.git_ops import apply_implementation_changes, implementation_file_paths

        changed = apply_implementation_changes(fix_result, repo_root=repo_path)

        if not changed:
            logger.warning("CI fix produced no file changes")
            git("checkout", gh_repo.default_branch, check=False, capture=True, cwd=repo_path)
            return {
                "fixed": False,
                "summary": "CI fix produced no file changes.",
                "fixes_applied": [],
            }

        # Stage and commit
        git("add", "-u", ".", check=False, capture=True, cwd=repo_path)
        for path in implementation_file_paths(fix_result):
            p = Path(repo_path) / path
            if p.exists():
                git("add", path, check=False, capture=True, cwd=repo_path)
        new_files = git("ls-files", "--others", "--exclude-standard",
                         capture=True, check=False, cwd=repo_path).stdout.strip()
        for nf in new_files.splitlines():
            git("add", nf, check=False, capture=True, cwd=repo_path)

        diff_check = git("diff", "--cached", "--name-only",
                          capture=True, check=False, cwd=repo_path).stdout.strip()
        if not diff_check:
            git("checkout", gh_repo.default_branch, check=False, capture=True, cwd=repo_path)
            return {
                "fixed": False,
                "summary": "No changes to commit after CI fix.",
                "fixes_applied": [],
            }

        commit_msg = fix_result.get(
            "commit_message",
            f"fix: CI failure on PR #{pr_number}",
        )
        git("commit", "-m", commit_msg, check=False, capture=True, cwd=repo_path)

        # Push to same branch
        if gh_token:
            remote_url = f"https://x-access-token:{gh_token}@github.com/{repo}.git"
            git("remote", "set-url", "origin", remote_url,
                check=False, capture=True, cwd=repo_path)

        git("push", "origin", f"HEAD:{pr.head.ref}",
            check=False, capture=True, cwd=repo_path)

        # Comment on the PR
        files_list = ", ".join(f"`{f}`" for f in changed)
        pr.create_issue_comment(
            f"🤖 **RepoKeeper CI Monitor** detected a CI failure and pushed a fix.\n\n"
            f"**Check:** {check.name} (failed)\n"
            f"**Fix:** {fix_result.get('summary', 'CI fix applied.')}\n"
            f"**Changed:** {files_list}\n"
            f"**Commit:** `{commit_msg}`\n\n"
            f"CI will re-run automatically."
        )

        git("checkout", gh_repo.default_branch, check=False, capture=True, cwd=repo_path)

        return {
            "fixed": True,
            "summary": fix_result.get("summary", "CI fix applied."),
            "fixes_applied": changed,
        }

    except Exception as exc:
        logger.error("CI monitoring fix failed for PR #%d: %s", pr_number, exc)
        try:
            gh_repo = gh_client.get_repo(repo)
            pr = gh_repo.get_pull(pr_number)
            pr.create_issue_comment(
                f"🤖 **RepoKeeper CI Monitor** detected a CI failure but could not "
                f"fix it automatically.\n\n"
                f"**Error:** {exc}\n\n"
                f"Please investigate manually.\n"
                f"Check run: {check.url}"
            )
        except Exception:
            pass
        return {
            "fixed": False,
            "summary": f"CI monitoring error: {exc}",
            "fixes_applied": [],
        }


def run_ci_monitor(
    gh_client: Any,
    llm: LLMClient,
    repo: str,
    profile: dict | None = None,
    max_prs: int = 10,
    repo_path: Path = Path("."),
    gh_token: str | None = None,
) -> dict[str, Any]:
    """Monitor CI on all agent PRs and auto-fix failures.

    Args:
        gh_client: PyGithub Github instance.
        llm: LLM client.
        repo: Repository slug.
        profile: Maintainer profile.
        max_prs: Maximum PRs to check.
        repo_path: Local repo path.
        gh_token: GitHub token for push access.

    Returns:
        Dict with ``prs_checked``, ``prs_fixed``, ``details``.
    """
    if profile is None:
        profile = load_profile()

    patrol_config = profile.get("patrol", {})
    if not patrol_config.get("ci_auto_fix", True):
        return {"prs_checked": 0, "prs_fixed": 0, "details": [], "reason": "ci_auto_fix disabled"}

    agent_prs = find_agent_prs(gh_client, repo, max_prs=max_prs)
    logger.info("CI Monitor: found %d agent PRs to check", len(agent_prs))

    details: list[dict[str, Any]] = []
    fixed_count = 0

    for pr_number in agent_prs:
        status = get_pr_check_status(gh_client, repo, pr_number)
        detail = {
            "pr_number": pr_number,
            "overall": status.overall,
            "total_checks": status.total_checks,
            "failed_count": len(status.failed),
        }

        if status.overall == "failure":
            logger.info("PR #%d has %d failing checks — attempting auto-fix", pr_number, len(status.failed))
            fix = diagnose_and_fix_ci(gh_client, llm, repo, pr_number, profile, repo_path)
            detail["fix_applied"] = fix.get("fixed", False)
            detail["fix_summary"] = fix.get("summary", "")
            if fix.get("fixed"):
                fixed_count += 1
        else:
            detail["fix_applied"] = False

        details.append(detail)

    return {
        "prs_checked": len(agent_prs),
        "prs_fixed": fixed_count,
        "details": details,
    }
